#!/bin/sh /etc/rc.common

START=99 # after mobilus

USE_PROCD=1
PROG=/opt/jungi/bin/moblink
CONF=/opt/jungi/etc/moblink.conf

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param file $CONF
    procd_set_param stdout 1
    procd_set_param stderr 1

    while IFS= read -r line; do
        case "$line" in
            ''|\#*) continue ;;
        esac
        procd_append_param env "$line"
    done < $CONF

    procd_close_instance
}
