name: Linux Build

on:
  push:
    branches: ['github-build']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5

    - name: Common strings
      id: strings
      shell: bash
      run: |
        echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "exec=${{ github.workspace }}/build/moblink-linux-$(uname -m)" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libmosquitto-dev libssl-dev

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -B ${{ steps.strings.outputs.build-dir }} -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-dir }}

    - name: Strip
      run: strip ${{ steps.strings.outputs.build-dir }}/moblink

    - name: Prepare package
      run: |
        mkdir ${{ steps.strings.outputs.build-dir }}/package
        cp ${{ steps.strings.outputs.build-dir }}/moblink ${{ steps.strings.outputs.build-dir }}/package
        cp ${{ github.workspace }}/packaging/deb/moblink.conf ${{ steps.strings.outputs.build-dir }}/package
        cp ${{ github.workspace }}/packaging/deb/moblink.service ${{ steps.strings.outputs.build-dir }}/package

    - name: Create package
      run: tar -czvf ${{ steps.strings.outputs.build-dir }}/moblink-linux.tar.gz -C ${{ steps.strings.outputs.build-dir }}/package .

    - name: Rename
      run: mv ${{ steps.strings.outputs.build-dir }}/moblink ${{ steps.strings.outputs.exec }}

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.strings.outputs.exec }}
          ${{ steps.strings.outputs.build-dir }}/moblink-linux.tar.gz
